// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/models/food_entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5036176211723781960),
      name: 'FoodEntry',
      lastPropertyId: const obx_int.IdUid(8, 8812083681162892971),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8992690024817235395),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 241851058416172079),
            name: 'uuid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 6616730479755630431)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1011917457897121981),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3969937394287829318),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7750552175114802352),
            name: 'isVegetarian',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8875568746158179980),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2237155335761880813),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8812083681162892971),
            name: 'isSynced',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5036176211723781960),
      lastIndexId: const obx_int.IdUid(1, 6616730479755630431),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    FoodEntry: obx_int.EntityDefinition<FoodEntry>(
        model: _entities[0],
        toOneRelations: (FoodEntry object) => [],
        toManyRelations: (FoodEntry object) => {},
        getId: (FoodEntry object) => object.id,
        setId: (FoodEntry object, int id) {
          object.id = id;
        },
        objectToFB: (FoodEntry object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final nameOffset = fbb.writeString(object.name);
          final categoryOffset = fbb.writeString(object.category);
          final imageUrlOffset = object.imageUrl == null
              ? null
              : fbb.writeString(object.imageUrl!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, categoryOffset);
          fbb.addBool(4, object.isVegetarian);
          fbb.addOffset(5, imageUrlOffset);
          fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
          fbb.addBool(7, object.isSynced);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uuidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final isVegetarianParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final isSyncedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final object = FoodEntry(
              id: idParam,
              uuid: uuidParam,
              name: nameParam,
              category: categoryParam,
              isVegetarian: isVegetarianParam,
              imageUrl: imageUrlParam,
              timestamp: timestampParam,
              isSynced: isSyncedParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FoodEntry] entity fields to define ObjectBox queries.
class FoodEntry_ {
  /// See [FoodEntry.id].
  static final id =
      obx.QueryIntegerProperty<FoodEntry>(_entities[0].properties[0]);

  /// See [FoodEntry.uuid].
  static final uuid =
      obx.QueryStringProperty<FoodEntry>(_entities[0].properties[1]);

  /// See [FoodEntry.name].
  static final name =
      obx.QueryStringProperty<FoodEntry>(_entities[0].properties[2]);

  /// See [FoodEntry.category].
  static final category =
      obx.QueryStringProperty<FoodEntry>(_entities[0].properties[3]);

  /// See [FoodEntry.isVegetarian].
  static final isVegetarian =
      obx.QueryBooleanProperty<FoodEntry>(_entities[0].properties[4]);

  /// See [FoodEntry.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<FoodEntry>(_entities[0].properties[5]);

  /// See [FoodEntry.timestamp].
  static final timestamp =
      obx.QueryDateProperty<FoodEntry>(_entities[0].properties[6]);

  /// See [FoodEntry.isSynced].
  static final isSynced =
      obx.QueryBooleanProperty<FoodEntry>(_entities[0].properties[7]);
}
